version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: empresa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_notebook
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "q6aa@g#5apHX2D$%8qo1"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - postgres

volumes:
  postgres_data: